# Generated by Django 3.0.4 on 2020-04-29 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salalem', '0002_auto_20200429_0552'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=200)),
                ('album_year', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Albums',
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Artists',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(max_length=200)),
                ('song_path', models.CharField(max_length=200)),
                ('song_album', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='salalem.Album', verbose_name='Albums')),
            ],
        ),
        migrations.DeleteModel(
            name='lists',
        ),
        migrations.AddField(
            model_name='album',
            name='album_artist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='salalem.Artist', verbose_name='Artists'),
        ),
    ]
