# Generated by Django 3.0.4 on 2020-05-01 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salalem', '0003_auto_20200429_2157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={},
        ),
    ]
