# Generated by Django 3.0.4 on 2020-05-01 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salalem', '0004_auto_20200501_0457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'verbose_name_plural': 'Artists'},
        ),
    ]
